# Generated by Django 6.1.2 on 2026-10-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('khoroo', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('air', models.IntegerField()),
                ('water', models.IntegerField()),
                ('heat', models.IntegerField()),
                ('traffic', models.IntegerField()),
                ('noise', models.IntegerField()),
            ],
        ),
    ]
