# Generated by Django 6.1.2 on 2026-10-07 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='property',
            name='air',
        ),
        migrations.RemoveField(
            model_name='property',
            name='district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='heat',
        ),
        migrations.RemoveField(
            model_name='property',
            name='khoroo',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='property',
            name='noise',
        ),
        migrations.RemoveField(
            model_name='property',
            name='traffic',
        ),
        migrations.RemoveField(
            model_name='property',
            name='water',
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
