# Generated by Django 6.1.2 on 2026-10-07 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comfortweights_complexcomment_complexrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexrating',
            name='explanation_comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='core.complexcomment'),
        ),
    ]
