# Generated by Django 6.1.2 on 2026-10-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_complexrating_explanation_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
