# Generated by Django 6.1.2 on 2026-10-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='remote_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
